//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <R.h>
#include <Rinternals.h>
#include "mn.h"

using namespace Rcpp;

//[[Rcpp::export]]
SEXP vecdist(SEXP x){
  int nrow,ncol;
  nrow=ncol=LENGTH(x);
  SEXP F=PROTECT(Rf_allocMatrix(REALSXP,ncol,nrow));
  double *xx=REAL(x),*end=xx+nrow,*f=REAL(F),*y=xx;
  for(;xx!=end;++xx,f+=nrow)
    minus_c(f,*xx,y,1,ncol);
  UNPROTECT(1);
  return F;
}

RcppExport SEXP Rfast_vecdist(SEXP x){
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    __result = vecdist(x);
    return __result;
END_RCPP
}