# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
#[export]
total.dista <- function(x,y,square = FALSE) {
    .Call(Rfast_total_dista,t(x),t(y),square)
}